id: D2CA700B4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:50:14+00:00'
last_modified: '2022-05-27T15:23:57.172319+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    4a82:
      image_group_id: I1PD95909
      title: བྱང་ཆུབ་ལམ་གྱི་སྒྲོན་མ།
      total_pages: 1902
      order: 64
      base_file: 4a82.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
