id: PD93D56DD
initial_creation_type: ocr
source_metadata:
  volumes:
    6b953ae7a3b342ab92db0b078d7c0542:
      base_file: v064.txt
      image_group_id: I1PD95909
      title: བྱང་ཆུབ་ལམ་གྱི་སྒྲོན་མ།
      total_pages: 1902
      volume_number: 64
